---
title: "each_plots_bar_graph"
author: "Yagi_Masato"
date: "2019/11/30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install library}
setwd("C:/Users/yagin/Google ドライブ/graphic_code")
library(ggplot2)
library(xlsx)
```

```{r make_func}
st.err <- function(x){
  sd(x)/sqrt(length(x))
}
```

```{r}
title_label <- ""
x_label <- ""
y_label <- "AUC(mm × min)"
p_value <- "p=0.97"
annotate_x <- 0.5
annotate_y <- 6500
annotate_size <- ""
y_axis_scale <- seq(0,7000,by=1000)
#jitterなし
```

試行錯誤用
```{r}
data_AUC <- read.xlsx("data_Bar_graphs3_paired_raw_plots.xlsx",1)
f <- ggplot(data_AUC, aes(y=AUC,x=Condition,shape=subject))
  #棒グラフの設定
f <- f + stat_summary(geom="bar",fun.y="mean",width=0.5,fill="gray") + 
  #実データ,エラーバーの設定
  stat_summary(fun.y="mean",fun.ymin = function(x)mean(x)-st.err(x),
               fun.ymax = function(x)mean(x)+st.err(x),geom="errorbar",width=0.2)
  # plotの色を離散的に(+色を変えている)
f <- f + geom_point(size=3) +
  scale_shape_manual(values=c(0,1,2,3,4,5,6))
  # guides(fill=FALSE) +
f <- f + theme_set(theme_classic(base_size = 18, base_family = "Helvetica")) +
  labs(title=title_label,x=x_label,y=y_label) +
  scale_y_continuous(breaks=seq(0,7000,by=1000))
#ラベルと題名
f <- f + theme(plot.title=element_text(hjust=0.5), #題名の位置とフォント
         panel.grid.major=element_blank(), #背景の削除
         panel.grid.minor=element_blank(),
         panel.background=element_blank(),
         axis.line=element_line(colour="black"), #軸の色の変更
         axis.ticks=element_line(colour="black"),
         axis.text=element_text(size=12),
         #軸のタイトルとラベルの文字サイズの変更
         axis.title=element_text(size=14,face="bold"))
f
```


