---
title: "line_graph"
author: "Yagi_Masato"
date: "2019/11/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Markdown
折れ線グラフ
エラーバーが重なった時用(ずらしてある)
3条件

```{r load}
  setwd("C:/Users/yagin/Google ドライブ/graphic_code/code_sample")
  library(ggplot2)
  library(xlsx)
  library(plyr)
```

```{r 変数}
  tg <- read.xlsx("polylines_3_no_doubled.xlsx", 4)
  tg$Time <- factor(tg$Time,levels=c("PRE","POST","15","30","45","60","75"))
  #Timeのfactorの並び替え
  tg$Condition <- factor(tg$Condition,levels=c("Placebo","BCAA","Trp"))
  str(tg)
  title_label <- "満足感"
  pd=position_dodge(0.2)
  x_label <- "Time(min)"
  y_label <- "VAS(mm)"
  label_tag <- "Group effect  p=0.300\nTime effect   p=0.150\nGroup×Time p=0.280"
```

```{r}
# par(family="HiraKaku")
f <- ggplot(tg, aes(x=Time,y=VAS,fill=Condition,shape=Condition,group=Condition))
f <- f + geom_line(position=pd,colour="black")
f <- f + geom_errorbar(aes(ymin=VAS-se,ymax=VAS+se),width=.2,size=0.25,colour="black",position=pd)
f <- f + geom_point(position=pd,size=3,colour="black")
#目盛
f <- f + scale_y_continuous(breaks=seq(0,100,10),labels=seq(0,100,10),limits=c(0,100))
f <- f + labs(title=title_label,x=x_label,y=y_label) #ラベルと題名
f <- f + theme(plot.title=element_text(hjust=0.5), #題名の位置とフォント
         panel.grid.major=element_blank(), #背景の削除
         panel.grid.minor=element_blank(),
         panel.background=element_blank(),
         axis.line=element_line(colour="black"), #軸の色の変更
         axis.ticks=element_line(colour="black"),
         axis.text=element_text(size=12), #軸のタイトルとラベルの文字サイズの変更
         axis.title=element_text(size=14,face="bold"))
f <- f + annotate("text",x=1,y=90,lineheight=1.0,hjust=0, #注釈
  label=label_tag)+
  scale_fill_manual(values=c("black","white","gray"))+ #デフォルトの色を変更
  scale_shape_manual(values=c(21,22,24)) #デフォルトの点を変更(枠線あり)
ggsave(file = "polylines_3_no_doubled.png", plot = f, dpi = 100, width = 7.0, height = 4.3)
```



